// Ignore Spelling: dbo

// <auto-generated />
#nullable disable

namespace Infrastructure.Database.Migrations;
using Microsoft.EntityFrameworkCore.Migrations;

/// <inheritdoc />
public partial class Create_Database : Migration
{
	/// <inheritdoc />
	protected override void Up(MigrationBuilder migrationBuilder)
	{
		_ = migrationBuilder.EnsureSchema(
			name: "dbo");

		_ = migrationBuilder.CreateTable(
			name: "users",
			columns: table => new
			{
				id = table.Column<Guid>(type: "UNIQUEIDENTIFIER", nullable: false),
				email = table.Column<string>(type: "VARCHAR(320)", nullable: false),
				first_name = table.Column<string>(type: "NVARCHAR(255)", nullable: false),
				last_name = table.Column<string>(type: "NVARCHAR(255)", nullable: false),
				password_hash = table.Column<string>(type: "NVARCHAR(MAX)", nullable: false)
			},
			schema: "dbo",
			constraints: table =>
			{
				_ = table.PrimaryKey("pk_users", x => x.id);
			});

		_ = migrationBuilder.CreateTable(
			name: "todo_items",
			columns: table => new
			{
				id = table.Column<Guid>(type: "UNIQUEIDENTIFIER", nullable: false),
				user_id = table.Column<Guid>(type: "UNIQUEIDENTIFIER", nullable: false),
				description = table.Column<string>(type: "NVARCHAR(MAX)", nullable: false),
				due_date = table.Column<DateTime>(type: "DATETIMEOFFSET", nullable: true),
				labels = table.Column<List<string>>(type: "NVARCHAR(MAX)", nullable: false),
				is_completed = table.Column<bool>(type: "BIT", nullable: false),
				created_at = table.Column<DateTime>(type: "DATETIMEOFFSET", nullable: false),
				completed_at = table.Column<DateTime>(type: "DATETIMEOFFSET", nullable: true),
				priority = table.Column<int>(type: "SMALLINT", nullable: false)
			},
			schema: "dbo",
			constraints: table =>
			{
				_ = table.PrimaryKey("pk_todo_items", x => x.id);
				_ = table.ForeignKey(
					name: "fk_todo_items_users_user_id",
					column: x => x.user_id,
					principalTable: "users",
					principalColumn: "id", principalSchema: "dbo",
					onDelete: ReferentialAction.Cascade);
			});

		_ = migrationBuilder.CreateIndex(
			name: "ix_todo_items_user_id",
			table: "todo_items",
			column: "user_id",
			schema: "dbo");

		_ = migrationBuilder.CreateIndex(
			name: "ix_users_email",
			table: "users",
			column: "email",
			schema: "dbo",
			unique: true);
	}

	/// <inheritdoc />
	protected override void Down(MigrationBuilder migrationBuilder)
	{
		_ = migrationBuilder.DropTable(
			name: "todo_items",
			schema: "dbo");

		_ = migrationBuilder.DropTable(
			name: "users",
			schema: "dbo");
	}
}
